### PR TITLE
Fix eclipse warnings

### PR DESCRIPTION
**Pull request by katheris**
Changes made:
 - add java compile and target properties to set java level to 8
 - Remove unuses imports from test classes in the skeleton, rest and springboot
 - remove doctype from html file
 - add doctype to ibm-web-ext.xml file
 - change groupId of myArtifactId-bluemix and myArtifactId-localServer so they aren't a duplicate of the parent
 - remove versions from sub projects so they inherit from the parent

---
This change is [Reviewable](https://reviewable.io/reviews/wasdev/tool.accelerate.core/39)

### CODE REVIEW

**Comment by jgawor** [comment]
A few minor comments:
* Don't need to define `license`, `scm`, and certain `properties` in the child poms. Just define it once in the parent pom. Also check if the `scm` values are correct.
* Instead of specifying versions of different plugins within child poms, just define them in `pluginManagement` section of the parent pom and remove the versions from child poms. That will ensure consistent plugin versions in all your poms.
* And if set source & target compile level to `1.8` it might make sense to also setup enforcer plugin to require Java 8 when building the project.

**Comment by katheris** [comment]
Thanks @jgawor, I'll take a look at those. Is there a nice way to get rid of the m2e error messages? The ones relating to plugin goals not being recognised in the m2e lifecycle? I know you can add code to have them executed or ignored, but can we have them permanently added to m2e?

**Comment by ebullient** [comment]
Reviewed 68 of 70 files at r1.
Review status: 47 of 49 files reviewed at latest revision, 8 unresolved discussions.

---

*[liberty-starter-application/skeletons/v2/base/myProject-application/pom.xml, line 19 \[r1\]](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/39#-KHzG9I9gRbgJK2Z-HUk:-KHzG9IASUCKJOmrazXE:-191143104) ([raw file](https://github.com/wasdev/tool.accelerate.core/blob/bb1607626d477c5f5b7991d1b404267669173603/liberty-starter-application/skeletons/v2/base/myProject-application/pom.xml#L19)):*
> ```XML
>         <license>
>             <name>The Apache Software License, Version 2.0</name>
>             <url>https://raw.github.com/WASdev/tool.artisan.core/master/LICENSE</url>
> ```

artisan --> accelerate

---

*[liberty-starter-application/skeletons/v2/base/myProject-deploy/pom.xml, line 19 \[r1\]](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/39#-KHzGOIkHyWiGI37g4D2:-KHzGOIkHyWiGI37g4D3:-126229791) ([raw file](https://github.com/wasdev/tool.accelerate.core/blob/bb1607626d477c5f5b7991d1b404267669173603/liberty-starter-application/skeletons/v2/base/myProject-deploy/pom.xml#L19)):*
> ```XML
>         <license>
>             <name>The Apache Software License, Version 2.0</name>
>             <url>https://raw.github.com/WASdev/tool.artisan.core/master/LICENSE</url>
> ```

artisan -> accelerate

---

*[liberty-starter-application/skeletons/v2/base/myProject-deploy/myProject-bluemix/pom.xml, line 19 \[r1\]](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/39#-KHzGS_1bLB3dP8yePxK:-KHzGS_1bLB3dP8yePxL:-126229791) ([raw file](https://github.com/wasdev/tool.accelerate.core/blob/bb1607626d477c5f5b7991d1b404267669173603/liberty-starter-application/skeletons/v2/base/myProject-deploy/myProject-bluemix/pom.xml#L19)):*
> ```XML
>         <license>
>             <name>The Apache Software License, Version 2.0</name>
>             <url>https://raw.github.com/WASdev/tool.artisan.core/master/LICENSE</url>
> ```

artisan -> accelerate

---

*[liberty-starter-application/skeletons/v2/base/myProject-deploy/myProject-bluemix/pom.xml, line 72 \[r1\]](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/39#-KHzGVLp_3QWUfMnkUSi:-KHzGVLp_3QWUfMnkUSj:-1594630042) ([raw file](https://github.com/wasdev/tool.accelerate.core/blob/bb1607626d477c5f5b7991d1b404267669173603/liberty-starter-application/skeletons/v2/base/myProject-deploy/myProject-bluemix/pom.xml#L72)):*
> ```XML
>                                 <requireProperty>
>                                     <property>cf.org</property>
>                                     <message>The cf.org property must be
> ```

This wrapping doesn't look good on command line, consider tweaking

---

*[liberty-starter-application/skeletons/v2/base/myProject-deploy/myProject-bluemix/pom.xml, line 104 \[r1\]](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/39#-KHzGcVb-LXGtRwuWMFe:-KHzGcVb-LXGtRwuWMFf:1572239321) ([raw file](https://github.com/wasdev/tool.accelerate.core/blob/bb1607626d477c5f5b7991d1b404267669173603/liberty-starter-application/skeletons/v2/base/myProject-deploy/myProject-bluemix/pom.xml#L104)):*
> ```XML
>                         <configuration>
>                             <tasks>
>                                 <echo>Running bluemix profile with the following properties:
> ```

Similar: make sure this wrapping looks ok on command line

---

*[liberty-starter-application/skeletons/v2/base/myProject-deploy/myProject-localServer/pom.xml, line 19 \[r1\]](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/39#-KHzGjP9Me2yLd7PkmbA:-KHzGjP9Me2yLd7PkmbB:381844199) ([raw file](https://github.com/wasdev/tool.accelerate.core/blob/bb1607626d477c5f5b7991d1b404267669173603/liberty-starter-application/skeletons/v2/base/myProject-deploy/myProject-localServer/pom.xml#L19)):*
> ```XML
>         <license>
>             <name>The Apache Software License, Version 2.0</name>
>             <url>https://raw.github.com/WASdev/tool.artisan.core/master/LICENSE</url>
> ```

artisan -> accelerator

---

*[liberty-starter-application/skeletons/v2/base/myProject-deploy/myProject-localServer/pom.xml, line 178 \[r1\]](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/39#-KHzH9YP3s74bU6St9G-:-KHzH9YP3s74bU6St9G0:1429893616) ([raw file](https://github.com/wasdev/tool.accelerate.core/blob/bb1607626d477c5f5b7991d1b404267669173603/liberty-starter-application/skeletons/v2/base/myProject-deploy/myProject-localServer/pom.xml#L178)):*
> ```XML
>                                             <property>install.directory</property>
>                                             <message>The
>                                                 install.directory
> ```

wrapping -- make sure this looks ok

---

*[liberty-starter-application/skeletons/v2/base/myProject-wlpcfg/pom.xml, line 19 \[r1\]](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/39#-KHzHGSTOYM-8b-T-Etg:-KHzHGSTOYM-8b-T-Eth:-126229791) ([raw file](https://github.com/wasdev/tool.accelerate.core/blob/bb1607626d477c5f5b7991d1b404267669173603/liberty-starter-application/skeletons/v2/base/myProject-wlpcfg/pom.xml#L19)):*
> ```XML
>         <license>
>             <name>The Apache Software License, Version 2.0</name>
>             <url>https://raw.github.com/WASdev/tool.artisan.core/master/LICENSE</url>
> ```

artisan -> accelerate

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/39)*

**Comment by ebullient** [comment]
That is an alternate way to address my comments re: URL... removing them works. ;)

<details><summary><i>Previously, katheris (Katherine Stanley) wrote…</i></summary>
> Thanks @jgawor, I'll take a look at those. Is there a nice way to get rid of the m2e error messages? The ones relating to plugin goals not being recognised in the m2e lifecycle? I know you can add code to have them executed or ignored, but can we have them permanently added to m2e?</details>


---

Review status: 47 of 49 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/39#-:-KHzHsdi64cspOZWF8dE:-1351611850)*

**Comment by ebullient** [comment]
Reviewed 2 of 70 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/39)*

**Comment by ebullient** [comment]
Not as sure about requirement for cc/license thing in generated snippets: makes the files way longer than they need to be (feels wasteful and unnecessary), but... 

<details><summary><i>Previously, ebullient (Erin Schnabel) wrote…</i></summary>
> That is an alternate way to address my comments re: URL... removing them works. ;)
</details>


---

Reviewed 1 of 70 files at r1, 49 of 49 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/39#-:-KJ5naksCy-NTFQsLeSL:-863460083)*

**Pull request merged**
