### PR TITLE
Add GitHub integration

### PR DESCRIPTION
**Pull request by iainduncani**
Can view the output here:

https://github.com/iainduncani/TestAppAcceleratorProject

---
This change is [Reviewable](https://reviewable.io/reviews/wasdev/tool.accelerate.core/126)

### CODE REVIEW

**Comment by iainduncani** [comment]
This is now up on staging so you can poke it. To do so you need to create a GitHub OAuth token from here:

https://github.com/settings/tokens

Then call:

http://app-accel-staging.mybluemix.net/start/api/v1/createGitHubRepository?tech=rest&deploy=local&name=LibertyProjectWithRest2&build=GRADLE&workspace=fa398066-fda1-46a9-8ab3-3ff8ff15ae69&oAuthToken=<TOKEN>

**Comment by katheris** [comment]
Reviewed 2 of 12 files at r1.
Review status: 2 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

*[liberty-starter-application/src/main/java/com/ibm/liberty/starter/GitHubConnector.java, line 81 at r1](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/126#-KZaxLJ-zqgY2ggxzqnY:-KZaxLJ-zqgY2ggxzqnZ:bo1qpfz) ([raw file](https://github.com/wasdev/tool.accelerate.core/blob/189f7c1957df9b1eead8ef908359f79f5ac5043c/liberty-starter-application/src/main/java/com/ibm/liberty/starter/GitHubConnector.java#L81)):*
> ```Java
>     }
> 
>     public String getRepsoitoryLocation() {
> ```

Spelling mistake ^

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/126)*

**Comment by katheris** [comment]
Reviewed 2 of 12 files at r1.
Review status: 4 of 12 files reviewed at latest revision, 9 unresolved discussions.

---

*[liberty-starter-application/src/main/java/com/ibm/liberty/starter/GitHubConnector.java, line 1 at r1](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/126#-KZaxxB2Sp_Md8AkepEg:-KZaxxB34ZRdgt14zQU2:b-dk8tp4) ([raw file](https://github.com/wasdev/tool.accelerate.core/blob/189f7c1957df9b1eead8ef908359f79f5ac5043c/liberty-starter-application/src/main/java/com/ibm/liberty/starter/GitHubConnector.java#L1)):*
> ```Java
> package com.ibm.liberty.starter;
> ```

copyright missing

---

*[liberty-starter-application/src/main/java/com/ibm/liberty/starter/GitHubWriter.java, line 2 at r1](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/126#-KZaxywaX5YDU5MYWmtd:-KZaxywaX5YDU5MYWmte:b-dk8tp4) ([raw file](https://github.com/wasdev/tool.accelerate.core/blob/189f7c1957df9b1eead8ef908359f79f5ac5043c/liberty-starter-application/src/main/java/com/ibm/liberty/starter/GitHubWriter.java#L2)):*
> ```Java
> package com.ibm.liberty.starter;
> ```

copyright missing

---

*[liberty-starter-application/src/main/java/com/ibm/liberty/starter/ProjectConstructionInputData.java, line 1 at r1](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/126#-KZay-YXNtn6UP7UPxt1:-KZay-YXNtn6UP7UPxt2:b-dk8tp4) ([raw file](https://github.com/wasdev/tool.accelerate.core/blob/8a6204b1b3a5eca1c195bfa3571e698aa17210f0/liberty-starter-application/src/main/java/com/ibm/liberty/starter/ProjectConstructionInputData.java#L1)):*
> ```Java
> package com.ibm.liberty.starter;
> ```

copyright missing

---

*[liberty-starter-application/src/main/java/com/ibm/liberty/starter/build/gradle/CreateRepositoryTags.java, line 1 at r1](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/126#-KZay1PFLZql8Xjt6oW0:-KZay1PFLZql8Xjt6oW1:b-dk8tp4) ([raw file](https://github.com/wasdev/tool.accelerate.core/blob/8a6204b1b3a5eca1c195bfa3571e698aa17210f0/liberty-starter-application/src/main/java/com/ibm/liberty/starter/build/gradle/CreateRepositoryTags.java#L1)):*
> ```Java
> package com.ibm.liberty.starter.build.gradle;
> ```

copyright missing

---

*[liberty-starter-application/src/test/java/com/ibm/liberty/starter/it/api/v1/GitHubRepositoryCreationTest.java, line 1 at r1](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/126#-KZay3BDZ1042X59C2OE:-KZay3BDZ1042X59C2OF:b-dk8tp4) ([raw file](https://github.com/wasdev/tool.accelerate.core/blob/189f7c1957df9b1eead8ef908359f79f5ac5043c/liberty-starter-application/src/test/java/com/ibm/liberty/starter/it/api/v1/GitHubRepositoryCreationTest.java#L1)):*
> ```Java
> package com.ibm.liberty.starter.it.api.v1;
> ```

copyright missing

---

*[liberty-starter-application/src/test/java/com/ibm/liberty/starter/unit/GitHubWriterTest.java, line 1 at r1](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/126#-KZay4s6MM5GqdyzUhNX:-KZay4s6MM5GqdyzUhNY:b-dk8tp4) ([raw file](https://github.com/wasdev/tool.accelerate.core/blob/189f7c1957df9b1eead8ef908359f79f5ac5043c/liberty-starter-application/src/test/java/com/ibm/liberty/starter/unit/GitHubWriterTest.java#L1)):*
> ```Java
> package com.ibm.liberty.starter.unit;
> ```

copyright missing

---

*[liberty-starter-application/src/test/java/com/ibm/liberty/starter/unit/ProjectConstructionInputTest.java, line 1 at r1](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/126#-KZay7G4x2PHDWxDpKR3:-KZay7G4x2PHDWxDpKR4:b-dk8tp4) ([raw file](https://github.com/wasdev/tool.accelerate.core/blob/8a6204b1b3a5eca1c195bfa3571e698aa17210f0/liberty-starter-application/src/test/java/com/ibm/liberty/starter/unit/ProjectConstructionInputTest.java#L1)):*
> ```Java
> package com.ibm.liberty.starter.unit;
> ```

copyright missing

---

*[liberty-starter-application/src/test/java/com/ibm/liberty/starter/unit/SetupInitialConext.java, line 1 at r1](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/126#-KZay8wiFwpd4Ldavb85:-KZay8wiFwpd4Ldavb86:b-dk8tp4) ([raw file](https://github.com/wasdev/tool.accelerate.core/blob/189f7c1957df9b1eead8ef908359f79f5ac5043c/liberty-starter-application/src/test/java/com/ibm/liberty/starter/unit/SetupInitialConext.java#L1)):*
> ```Java
> package com.ibm.liberty.starter.unit;
> ```

copyright missing

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/126)*

**Comment by katheris** [comment]
Reviewed 3 of 12 files at r1, 45 of 45 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[liberty-starter-application/src/main/java/com/ibm/liberty/starter/api/v1/GitHubProjectEndpoint.java, line 45 at r1](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/126#-KZaydp4qZYCEyhPpyDH:-KZaydp4qZYCEyhPpyDI:b-pgs52f) ([raw file](https://github.com/wasdev/tool.accelerate.core/blob/189f7c1957df9b1eead8ef908359f79f5ac5043c/liberty-starter-application/src/main/java/com/ibm/liberty/starter/api/v1/GitHubProjectEndpoint.java#L45)):*
> ```Java
>             if (oAuthToken == null || oAuthToken.length() == 0) {
>                 log.severe("No oAuthToken passed in.");
>                 throw new ValidationException();
> ```

Should probably add validation to check that the auth token only has letters and numbers in to protect against malicious scripts

---

*[liberty-starter-wlpcfg/servers/StarterServer/resources/security/key.jks, line 0 at r2](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/126#-KZb1_odUoKEsChRQFlD:-KZb1_odUoKEsChRQFlE:b4ts5ma) ([raw file](https://github.com/wasdev/tool.accelerate.core/blob/d27b0986226edff4dd8b94a98801bb2c6bdea071/liberty-starter-wlpcfg/servers/StarterServer/resources/security/key.jks#L0)):*
Why has this file been checked in?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/126)*

**Comment by iainduncani** [comment]
Review status: 47 of 49 files reviewed at latest revision, 11 unresolved discussions.

---

*[liberty-starter-application/src/main/java/com/ibm/liberty/starter/GitHubConnector.java, line 1 at r1](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/126#-KZaxxB2Sp_Md8AkepEg:-KZb-SP7rQHwIKB8x8fA:b-896fix) ([raw file](https://github.com/wasdev/tool.accelerate.core/blob/189f7c1957df9b1eead8ef908359f79f5ac5043c/liberty-starter-application/src/main/java/com/ibm/liberty/starter/GitHubConnector.java#L1)):*
<details><summary><i>Previously, katheris (Katherine Stanley) wrote…</i></summary><blockquote>

copyright missing
</blockquote></details>

Done.

---

*[liberty-starter-application/src/main/java/com/ibm/liberty/starter/GitHubConnector.java, line 81 at r1](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/126#-KZaxLJ-zqgY2ggxzqnY:-KZb-Tvpp3sw_iiL-hGl:b-896fix) ([raw file](https://github.com/wasdev/tool.accelerate.core/blob/189f7c1957df9b1eead8ef908359f79f5ac5043c/liberty-starter-application/src/main/java/com/ibm/liberty/starter/GitHubConnector.java#L81)):*
<details><summary><i>Previously, katheris (Katherine Stanley) wrote…</i></summary><blockquote>

Spelling mistake ^
</blockquote></details>

Done.

---

*[liberty-starter-application/src/main/java/com/ibm/liberty/starter/GitHubWriter.java, line 2 at r1](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/126#-KZaxywaX5YDU5MYWmtd:-KZb3n1ZSV7Dbc1IipIK:b-896fix) ([raw file](https://github.com/wasdev/tool.accelerate.core/blob/189f7c1957df9b1eead8ef908359f79f5ac5043c/liberty-starter-application/src/main/java/com/ibm/liberty/starter/GitHubWriter.java#L2)):*
<details><summary><i>Previously, katheris (Katherine Stanley) wrote…</i></summary><blockquote>

copyright missing
</blockquote></details>

Done.

---

*[liberty-starter-application/src/main/java/com/ibm/liberty/starter/ProjectConstructionInputData.java, line 1 at r1](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/126#-KZay-YXNtn6UP7UPxt1:-KZb3oA4Gv_FY3KFMt21:b-896fix) ([raw file](https://github.com/wasdev/tool.accelerate.core/blob/8a6204b1b3a5eca1c195bfa3571e698aa17210f0/liberty-starter-application/src/main/java/com/ibm/liberty/starter/ProjectConstructionInputData.java#L1)):*
<details><summary><i>Previously, katheris (Katherine Stanley) wrote…</i></summary><blockquote>

copyright missing
</blockquote></details>

Done.

---

*[liberty-starter-application/src/main/java/com/ibm/liberty/starter/api/v1/GitHubProjectEndpoint.java, line 45 at r1](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/126#-KZaydp4qZYCEyhPpyDH:-KZb3qr-84hyDXT1O0C5:b-apv6r7) ([raw file](https://github.com/wasdev/tool.accelerate.core/blob/189f7c1957df9b1eead8ef908359f79f5ac5043c/liberty-starter-application/src/main/java/com/ibm/liberty/starter/api/v1/GitHubProjectEndpoint.java#L45)):*
<details><summary><i>Previously, katheris (Katherine Stanley) wrote…</i></summary><blockquote>

Should probably add validation to check that the auth token only has letters and numbers in to protect against malicious scripts
</blockquote></details>

Now encoding it. GitHub don't publish what format the token will take and it isn't part of the oAuth spec so don't think we can validate

---

*[liberty-starter-application/src/main/java/com/ibm/liberty/starter/build/gradle/CreateRepositoryTags.java, line 1 at r1](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/126#-KZay1PFLZql8Xjt6oW0:-KZb5S5dQmjnivag7X-G:b-896fix) ([raw file](https://github.com/wasdev/tool.accelerate.core/blob/8a6204b1b3a5eca1c195bfa3571e698aa17210f0/liberty-starter-application/src/main/java/com/ibm/liberty/starter/build/gradle/CreateRepositoryTags.java#L1)):*
<details><summary><i>Previously, katheris (Katherine Stanley) wrote…</i></summary><blockquote>

copyright missing
</blockquote></details>

Done.

---

*[liberty-starter-application/src/test/java/com/ibm/liberty/starter/it/api/v1/GitHubRepositoryCreationTest.java, line 1 at r1](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/126#-KZay3BDZ1042X59C2OE:-KZb5Sx8t7XFfJmOy4Pc:b-896fix) ([raw file](https://github.com/wasdev/tool.accelerate.core/blob/189f7c1957df9b1eead8ef908359f79f5ac5043c/liberty-starter-application/src/test/java/com/ibm/liberty/starter/it/api/v1/GitHubRepositoryCreationTest.java#L1)):*
<details><summary><i>Previously, katheris (Katherine Stanley) wrote…</i></summary><blockquote>

copyright missing
</blockquote></details>

Done.

---

*[liberty-starter-application/src/test/java/com/ibm/liberty/starter/unit/GitHubWriterTest.java, line 1 at r1](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/126#-KZay4s6MM5GqdyzUhNX:-KZb5TgFDecPTJHcT6Hf:b-896fix) ([raw file](https://github.com/wasdev/tool.accelerate.core/blob/189f7c1957df9b1eead8ef908359f79f5ac5043c/liberty-starter-application/src/test/java/com/ibm/liberty/starter/unit/GitHubWriterTest.java#L1)):*
<details><summary><i>Previously, katheris (Katherine Stanley) wrote…</i></summary><blockquote>

copyright missing
</blockquote></details>

Done.

---

*[liberty-starter-application/src/test/java/com/ibm/liberty/starter/unit/ProjectConstructionInputTest.java, line 1 at r1](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/126#-KZay7G4x2PHDWxDpKR3:-KZb5qmjhUx6b6c54F3N:b-896fix) ([raw file](https://github.com/wasdev/tool.accelerate.core/blob/8a6204b1b3a5eca1c195bfa3571e698aa17210f0/liberty-starter-application/src/test/java/com/ibm/liberty/starter/unit/ProjectConstructionInputTest.java#L1)):*
<details><summary><i>Previously, katheris (Katherine Stanley) wrote…</i></summary><blockquote>

copyright missing
</blockquote></details>

Done.

---

*[liberty-starter-application/src/test/java/com/ibm/liberty/starter/unit/SetupInitialConext.java, line 1 at r1](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/126#-KZay8wiFwpd4Ldavb85:-KZb5ruwZP8zp__O8j2k:b-896fix) ([raw file](https://github.com/wasdev/tool.accelerate.core/blob/189f7c1957df9b1eead8ef908359f79f5ac5043c/liberty-starter-application/src/test/java/com/ibm/liberty/starter/unit/SetupInitialConext.java#L1)):*
<details><summary><i>Previously, katheris (Katherine Stanley) wrote…</i></summary><blockquote>

copyright missing
</blockquote></details>

Done.

---

*[liberty-starter-wlpcfg/servers/StarterServer/resources/security/key.jks, line  at r2](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/126#-KZb1_odUoKEsChRQFlD:-KZb5u5d8tIz1uTHNM8H:b-s5zntl) ([raw file](https://github.com/wasdev/tool.accelerate.core/blob/d27b0986226edff4dd8b94a98801bb2c6bdea071/liberty-starter-wlpcfg/servers/StarterServer/resources/security/key.jks#L)):*
<details><summary><i>Previously, katheris (Katherine Stanley) wrote…</i></summary><blockquote>

Why has this file been checked in?
</blockquote></details>

Because it now has the GitHub certificate in it so we can communicate with GitHub

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/126)*

**Comment by katheris** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/126)*

**Pull request merged**
