### PR TITLE
Fix spelling of dependency.

### PR DESCRIPTION
**Pull request by katheris**
Fixes issue #94 Signed-off-by: Kate Stanley <katheris@uk.ibm.com>

---
This change is [Reviewable](https://reviewable.io/reviews/wasdev/tool.accelerate.core/97)

### CODE REVIEW

**Comment by iainduncani** [comment]
Reviewed 2 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[Dockerfile, line 1 at r1](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/97#-KWrp0ZvXuYFkAtmpn-k:-KWrp0ZvXuYFkAtmpn-l:b8r7frr) ([raw file](https://github.com/wasdev/tool.accelerate.core/blob/a3da6d3f64f083ac2b02ac450d3d2a9f077735be/Dockerfile#L1)):*
> ```Dockerfile
> FROM websphere-liberty:webProfile7
> ```

Was this file meant to be included? Not sure what it has to do with spelling mistakes!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/97)*

**Comment by iainduncani** [comment]
Reviewed 1 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/97)*

**Comment by katheris** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Dockerfile, line 1 at r1](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/97#-KWrp0ZvXuYFkAtmpn-k:-KWrq4C1ST4_8nk4iDco:bss4a2b) ([raw file](https://github.com/wasdev/tool.accelerate.core/blob/a3da6d3f64f083ac2b02ac450d3d2a9f077735be/Dockerfile#L1)):*
<details><summary><i>Previously, iainduncani wrote…</i></summary>
> Was this file meant to be included? Not sure what it has to do with spelling mistakes!
</details>
Removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/97)*

**Comment by katheris** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Dockerfile, line 1 at r1](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/97#-KWrp0ZvXuYFkAtmpn-k:-KWrq7A8PFI7rXD-F_vH:b-896fix) ([raw file](https://github.com/wasdev/tool.accelerate.core/blob/a3da6d3f64f083ac2b02ac450d3d2a9f077735be/Dockerfile#L1)):*
<details><summary><i>Previously, katheris (Katherine Stanley) wrote…</i></summary>
> Removed.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/97)*

**Comment by katheris** [comment]
Reviewed 1 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/97)*

**Pull request merged**
