### PR TITLE
Update internal requests to http

### PR DESCRIPTION
**Pull request by katheris**
Update service connector to make http requests internally.

---
This change is [Reviewable](https://reviewable.io/reviews/wasdev/tool.accelerate.core/147)

### CODE REVIEW

**Comment by MarkNSweep** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[liberty-starter-application/src/main/java/com/ibm/liberty/starter/ServiceConnector.java, line 150 at r1](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/147#-Kar2n7bdAnV6bLEBTJp:-Kar2n7bdAnV6bLEBTJq:b-kav0sc) ([raw file](https://github.com/wasdev/tool.accelerate.core/blob/7fe4a068c153a47195bd7e06bffedd0f547d276b/liberty-starter-application/src/main/java/com/ibm/liberty/starter/ServiceConnector.java#L150)):*
> ```Java
>     
>     private String urlConstructor(String extension, Service service) {
>     	System.out.println("Constructing url:" + internalServerHostPort + "+" + service.getEndpoint() + "+" + extension);
> ```

Remove sys out

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/147)*

**Comment by MarkNSweep** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/147#-:-Kar4CdipEtBqGV7Pyz-:bnfp4nl)*

**Comment by MarkNSweep** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[liberty-starter-application/src/main/java/com/ibm/liberty/starter/ServiceConnector.java, line 150 at r1](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/147#-Kar2n7bdAnV6bLEBTJp:-Kar4PSuGQK03f6Uzhpk:b32wtd) ([raw file](https://github.com/wasdev/tool.accelerate.core/blob/7fe4a068c153a47195bd7e06bffedd0f547d276b/liberty-starter-application/src/main/java/com/ibm/liberty/starter/ServiceConnector.java#L150)):*
<details><summary><i>Previously, MarkNSweep (Adam Pilkington) wrote…</i></summary><blockquote>

Remove sys out
</blockquote></details>

ok

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/147)*

**Comment by katheris** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[liberty-starter-application/src/main/java/com/ibm/liberty/starter/ServiceConnector.java, line 150 at r1](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/147#-Kar2n7bdAnV6bLEBTJp:-Kar4zeI5_CdFrgG6v6r:b-896fix) ([raw file](https://github.com/wasdev/tool.accelerate.core/blob/7fe4a068c153a47195bd7e06bffedd0f547d276b/liberty-starter-application/src/main/java/com/ibm/liberty/starter/ServiceConnector.java#L150)):*
<details><summary><i>Previously, MarkNSweep (Adam Pilkington) wrote…</i></summary><blockquote>

ok
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/147)*

**Comment by MarkNSweep** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/147#-:-Kar56AWUv7OCW-yRPDm:bnfp4nl)*

**Pull request merged**
