### PR TITLE
Add gradle build

### PR DESCRIPTION
**Pull request by iainduncani**
This change is [Reviewable](https://reviewable.io/reviews/wasdev/tool.accelerate.core/101)

### CODE REVIEW

**Comment by katheris** [comment]
Reviewed 7 of 53 files at r1, 1 of 1 files at r2.
Review status: 8 of 42 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[liberty-starter-application/skeletons/specialFiles/build.gradle, line 41 at r2](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/101#-KXePcTPVv2SouLWPTcs:-KXePcTPVv2SouLWPTct:b-mtd94p) ([raw file](https://github.com/wasdev/tool.accelerate.core/blob/b0aacde2584df4c0dca727d829c38bd6242aa588/liberty-starter-application/skeletons/specialFiles/build.gradle#L41)):*
> ```Gradle
>     cfHost = appName
>     cfContext = 'eu-gb.mybluemix.net'
>     cfTarget = 'https://api.eu-gb.bluemix.net'
> ```

We should make the default US South as that's what most people use by default, we also have an issue to change the maven pom files to reference US South by default.

---

*[liberty-starter-application/src/main/java/com/ibm/liberty/starter/ProjectZipConstructor.java, line 92 at r2](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/101#-KXeR4AuYkVtq7tQ-fdI:-KXeR4AvGbxNavX1v-zK:b-eyup41) ([raw file](https://github.com/wasdev/tool.accelerate.core/blob/b0aacde2584df4c0dca727d829c38bd6242aa588/liberty-starter-application/src/main/java/com/ibm/liberty/starter/ProjectZipConstructor.java#L92)):*
> ```Java
>         this.workspace = workspace;
>         this.buildType = buildType;
>     }
> ```

Need to make sure the UI always passes in a workspace.

---

*[liberty-starter-application/src/main/java/com/ibm/liberty/starter/ProjectZipConstructor.java, line 251 at r2](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/101#-KXeRJWsM10Ex_Y7y2Eb:-KXeRJWsM10Ex_Y7y2Ec:bl3gunq) ([raw file](https://github.com/wasdev/tool.accelerate.core/blob/b0aacde2584df4c0dca727d829c38bd6242aa588/liberty-starter-application/src/main/java/com/ibm/liberty/starter/ProjectZipConstructor.java#L251)):*
> ```Java
> 
>     private void addGradleFilesToMap() throws IOException {
>         Map<String, String> buildTags = new HashMap<>();
> ```

Need some logging.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/101)*

**Comment by iainduncani** [comment]
*[liberty-starter-application/src/main/java/com/ibm/liberty/starter/ProjectZipConstructor.java, line 92 at r2](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/101#-KXeR4AuYkVtq7tQ-fdI:-KXnhfdBcMgZIEnrxRg4:b-femp3x) ([raw file](https://github.com/wasdev/tool.accelerate.core/blob/b0aacde2584df4c0dca727d829c38bd6242aa588/liberty-starter-application/src/main/java/com/ibm/liberty/starter/ProjectZipConstructor.java#L92)):*
<details><summary><i>Previously, katheris (Katherine Stanley) wrote…</i></summary><blockquote>

Need to make sure the UI always passes in a workspace.
</blockquote></details>

The constructor I deleted was never used so I assume the UI always does and if it doesn't isn't any more broken now than it was already.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/101)*

**Comment by iainduncani** [comment]
Review status: 5 of 47 files reviewed at latest revision, 3 unresolved discussions.

---

*[liberty-starter-application/skeletons/specialFiles/build.gradle, line 41 at r2](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/101#-KXePcTPVv2SouLWPTcs:-KXq0SsKTYbI2iIutI7O:b-896fix) ([raw file](https://github.com/wasdev/tool.accelerate.core/blob/b0aacde2584df4c0dca727d829c38bd6242aa588/liberty-starter-application/skeletons/specialFiles/build.gradle#L41)):*
<details><summary><i>Previously, katheris (Katherine Stanley) wrote…</i></summary><blockquote>

We should make the default US South as that's what most people use by default, we also have an issue to change the maven pom files to reference US South by default.
</blockquote></details>

Done.

---

*[liberty-starter-application/src/main/java/com/ibm/liberty/starter/ProjectZipConstructor.java, line 251 at r2](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/101#-KXeRJWsM10Ex_Y7y2Eb:-KXq0PsJQ0l-B7nXMN5d:b-896fix) ([raw file](https://github.com/wasdev/tool.accelerate.core/blob/b0aacde2584df4c0dca727d829c38bd6242aa588/liberty-starter-application/src/main/java/com/ibm/liberty/starter/ProjectZipConstructor.java#L251)):*
<details><summary><i>Previously, katheris (Katherine Stanley) wrote…</i></summary><blockquote>

Need some logging.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/101)*

**Comment by katheris** [comment]
Reviewed 1 of 53 files at r1, 6 of 7 files at r3, 3 of 3 files at r4.
Review status: 15 of 47 files reviewed at latest revision, 2 unresolved discussions.

---

*[liberty-starter-application/src/main/java/com/ibm/liberty/starter/api/v1/LibertyTechnologySelector.java, line 102 at r4](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/101#-KXuTeX-hRVYSpuabjux:-KXuTeX-hRVYSpuabjuy:bowwu34) ([raw file](https://github.com/wasdev/tool.accelerate.core/blob/13e935a1e2f148266fd47314fb8c1618e03c5a81/liberty-starter-application/src/main/java/com/ibm/liberty/starter/api/v1/LibertyTechnologySelector.java#L102)):*
> ```Java
>                 buildType = BuildType.MAVEN;
>             }
> ```

We should validate this value first, to prevent people from putting in harmful requests.

---

*[liberty-starter-application/src/test/java/com/ibm/liberty/starter/it/api/v1/utils/DownloadedZip.java, line 94 at r4](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/101#-KXuU_2FR0gweUHGXU2U:-KXuU_2FR0gweUHGXU2V:b-4mlqfi) ([raw file](https://github.com/wasdev/tool.accelerate.core/blob/13e935a1e2f148266fd47314fb8c1618e03c5a81/liberty-starter-application/src/test/java/com/ibm/liberty/starter/it/api/v1/utils/DownloadedZip.java#L94)):*
> ```Java
>         assertThat(responseString, containsString("Welcome to your Liberty Application"));
>         assertThat(responseString, containsString("Test"));
>     }
> ```

What is this method for?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/101)*

**Comment by iainduncani** [comment]
*[liberty-starter-application/src/test/java/com/ibm/liberty/starter/it/api/v1/utils/DownloadedZip.java, line 94 at r4](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/101#-KXuU_2FR0gweUHGXU2U:-KXudCfGMMyZ4WqYfZqi:b4ygagt) ([raw file](https://github.com/wasdev/tool.accelerate.core/blob/13e935a1e2f148266fd47314fb8c1618e03c5a81/liberty-starter-application/src/test/java/com/ibm/liberty/starter/it/api/v1/utils/DownloadedZip.java#L94)):*
<details><summary><i>Previously, katheris (Katherine Stanley) wrote…</i></summary><blockquote>

What is this method for?
</blockquote></details>

This tests the application payload and has moved from the maven payload test as it is common for maven and gradle

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/101)*

**Comment by katheris** [comment]
Reviewed 43 of 53 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/101)*

**Pull request merged**
