### PR TITLE
Update to single project structure

### PR DESCRIPTION
**Pull request by iainduncani**
This change is [Reviewable](https://reviewable.io/reviews/wasdev/tool.accelerate.core/93)

### CODE REVIEW

**Comment by katheris** [comment]
Reviewed 1 of 82 files at r1.
Review status: 1 of 64 files reviewed at latest revision, 2 unresolved discussions.

---

*[README.md, line 27 at r1](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/93#-KWXz3Tv9jM9UiMe0W0W:-KWXz3Tv9jM9UiMe0W0X:beo6iej) ([raw file](https://github.com/wasdev/tool.accelerate.core/blob/2a0da3596b4843b220d283734b61bb83a08d7d29/README.md#L27)):*
> ```Markdown
> This provides you with a SpringBoot application that will run on WebSphere Liberty.
> 
> Inside the application project there is a application.springboot.web package containing two classes:
> ```

Need to remove the word application here

---

*[liberty-starter-application/build.gradle, line 138 at r1](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/93#-KWY0DSBcpcuOqiR1_vi:-KWY0DSBcpcuOqiR1_vj:bhs2n33) ([raw file](https://github.com/wasdev/tool.accelerate.core/blob/2a0da3596b4843b220d283734b61bb83a08d7d29/liberty-starter-application/build.gradle#L138)):*
> ```Gradle
>     file("${buildDir}/fvtRanSuccessfullyTrigger") << new Date()
> }
> ```

I don't think using << is a good idea. I think this is no longer deemed best practice and I am struggling to find documentation to say exactly what using the symbols does. It makes it harder for other people to understand our builds.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/93)*

**Comment by katheris** [comment]
Reviewed 1 of 82 files at r1.
Review status: 2 of 64 files reviewed at latest revision, 3 unresolved discussions.

---

*[README.md, line 68 at r1](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/93#-KWY0fbvrVIC-gDcozUT:-KWY0fbwt6CnnNhVCjJO:b7dniax) ([raw file](https://github.com/wasdev/tool.accelerate.core/blob/2a0da3596b4843b220d283734b61bb83a08d7d29/README.md#L68)):*
> ```Markdown
> 
> ## Building the Project
> Once you have downloaded the project, to build it you just need to run the command `gradle clean build` in the top level project. To run the application locally from the root project run `liberty-starter-application:forceRunLibertyStart liberty-starter-application:libertyStart -x check -x publishTestWar -x addServerEnv`. The application should be available at http://localhost:9082/start.
> ```

This is a really long command, we should explain what this is doing or do something simpler.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/93)*

**Comment by katheris** [comment]
Reviewed 1 of 82 files at r1.
Review status: 3 of 64 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/93)*

**Comment by katheris** [comment]
Reviewed 1 of 82 files at r1.
Review status: 4 of 64 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/93)*

**Comment by katheris** [comment]
Reviewed 1 of 82 files at r1.
Review status: 5 of 64 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/93)*

**Comment by katheris** [comment]
Reviewed 1 of 82 files at r1.
Review status: 6 of 64 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/93)*

**Comment by katheris** [comment]
Reviewed 1 of 82 files at r1.
Review status: 7 of 64 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/93)*

**Comment by katheris** [comment]
Reviewed 1 of 82 files at r1.
Review status: 8 of 64 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/93)*

**Comment by katheris** [comment]
Reviewed 1 of 82 files at r1.
Review status: 9 of 64 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/93)*

**Comment by katheris** [comment]
Reviewed 1 of 82 files at r1.
Review status: 10 of 64 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/93)*

**Comment by katheris** [comment]
Reviewed 2 of 82 files at r1.
Review status: 12 of 64 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/93)*

**Comment by katheris** [comment]
Reviewed 4 of 82 files at r1.
Review status: 14 of 64 files reviewed at latest revision, 4 unresolved discussions.

---

*[liberty-starter-application/skeletons/base/src/main/liberty/config/server.xml, line 18 at r1](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/93#-KWY1QU59dRiFK59-maC:-KWY1QU59dRiFK59-maD:b4t90j) ([raw file](https://github.com/wasdev/tool.accelerate.core/blob/2a0da3596b4843b220d283734b61bb83a08d7d29/liberty-starter-application/skeletons/base/src/main/liberty/config/server.xml#L18)):*
> ```XML
> 
> ```

Should this reference the target directory?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/93)*

**Comment by katheris** [comment]
Reviewed 2 of 82 files at r1.
Review status: 15 of 64 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/93)*

**Comment by katheris** [comment]
Reviewed 2 of 82 files at r1.
Review status: 16 of 64 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/93)*

**Comment by katheris** [comment]
Reviewed 2 of 82 files at r1.
Review status: 17 of 64 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/93)*

**Comment by katheris** [comment]
Reviewed 2 of 82 files at r1.
Review status: 18 of 64 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/93)*

**Comment by katheris** [comment]
Reviewed 4 of 82 files at r1.
Review status: 20 of 64 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/93)*

**Comment by katheris** [comment]
Review status: 20 of 64 files reviewed at latest revision, 6 unresolved discussions.

---

*[liberty-starter-application/skeletons/specialFiles/pom.xml, line 113 at r1](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/93#-KWY4dnKWNuVsBUQIYMK:-KWY4dnKWNuVsBUQIYML:b-bv6pug) ([raw file](https://github.com/wasdev/tool.accelerate.core/blob/2a0da3596b4843b220d283734b61bb83a08d7d29/liberty-starter-application/skeletons/specialFiles/pom.xml#L113)):*
> ```XML
>                         <groupId>org.apache.maven.plugins</groupId>
>                         <artifactId>maven-antrun-plugin</artifactId>
>                         <executions>
> ```

Where is the version for this being declared?

---

*[liberty-starter-application/skeletons/specialFiles/pom.xml, line 307 at r1](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/93#-KWY6kprf-vTeJ7krttE:-KWY6kprf-vTeJ7krttF:b-atslhh) ([raw file](https://github.com/wasdev/tool.accelerate.core/blob/2a0da3596b4843b220d283734b61bb83a08d7d29/liberty-starter-application/skeletons/specialFiles/pom.xml#L307)):*
> ```XML
>                             <goal>stop-server</goal>
>                         </goals>
>                     </execution>
> ```

We should consider putting this in a separate profile as if you run mvn install -DskipTests the tests will skip but the server will still start and stop.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/93)*

**Comment by katheris** [comment]
Review status: 20 of 64 files reviewed at latest revision, 8 unresolved discussions.

---

*[liberty-starter-application/skeletons/specialFiles/pom.xml, line 349 at r1](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/93#-KWY7cz9PJU6GxX2GH4F:-KWY7cz9PJU6GxX2GH4G:b-o6ignf) ([raw file](https://github.com/wasdev/tool.accelerate.core/blob/2a0da3596b4843b220d283734b61bb83a08d7d29/liberty-starter-application/skeletons/specialFiles/pom.xml#L349)):*
> ```XML
>                 </executions>
>                 <configuration>
>                     <summaryFile>${project.build.directory}/test-reports/fvt/failsafe-summary.xml</summaryFile>
> ```

We should change this to ${project.build.directory}/test-reports/it/failsafe-summary.xml to match the new package names.

---

*[liberty-starter-application/skeletons/specialFiles/pom.xml, line 350 at r1](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/93#-KWY7ldR5KeP2Iibi1yA:-KWY7ldR5KeP2Iibi1yB:b2nreh6) ([raw file](https://github.com/wasdev/tool.accelerate.core/blob/2a0da3596b4843b220d283734b61bb83a08d7d29/liberty-starter-application/skeletons/specialFiles/pom.xml#L350)):*
> ```XML
>                 <configuration>
>                     <summaryFile>${project.build.directory}/test-reports/fvt/failsafe-summary.xml</summaryFile>
>                     <reportsDirectory>${project.build.directory}/test-reports/fvt</reportsDirectory>
> ```

Same as above.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/93)*

**Comment by katheris** [comment]
Reviewed 1 of 82 files at r1.
Review status: 21 of 64 files reviewed at latest revision, 8 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/93)*

**Comment by katheris** [comment]
Reviewed 2 of 82 files at r1.
Review status: 23 of 64 files reviewed at latest revision, 8 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/93)*

**Comment by katheris** [comment]
Reviewed 1 of 82 files at r1.
Review status: 24 of 64 files reviewed at latest revision, 8 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/93)*

**Comment by katheris** [comment]
Reviewed 1 of 82 files at r1.
Review status: 25 of 64 files reviewed at latest revision, 8 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/93)*

**Comment by katheris** [comment]
Reviewed 1 of 82 files at r1.
Review status: 26 of 64 files reviewed at latest revision, 8 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/93)*

**Comment by katheris** [comment]
Reviewed 1 of 82 files at r1.
Review status: 27 of 64 files reviewed at latest revision, 8 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/93)*

**Comment by katheris** [comment]
Reviewed 1 of 82 files at r1.
Review status: 28 of 64 files reviewed at latest revision, 8 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/93)*

**Comment by katheris** [comment]
Reviewed 2 of 82 files at r1.
Review status: 29 of 64 files reviewed at latest revision, 8 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/93)*

**Comment by katheris** [comment]
Reviewed 1 of 82 files at r1.
Review status: 30 of 64 files reviewed at latest revision, 8 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/93)*

**Comment by katheris** [comment]
Reviewed 1 of 82 files at r1.
Review status: 31 of 64 files reviewed at latest revision, 8 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/93)*

**Comment by katheris** [comment]
Reviewed 1 of 82 files at r1.
Review status: 32 of 64 files reviewed at latest revision, 9 unresolved discussions.

---

*[liberty-starter-application/src/main/java/com/ibm/liberty/starter/pom/SetDefaultProfileCommand.java, line 28 at r1](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/93#-KWYErw1SHFTmIBkpyrC:-KWYErw1SHFTmIBkpyrD:bnq8rqt) ([raw file](https://github.com/wasdev/tool.accelerate.core/blob/2a0da3596b4843b220d283734b61bb83a08d7d29/liberty-starter-application/src/main/java/com/ibm/liberty/starter/pom/SetDefaultProfileCommand.java#L28)):*
> ```Java
>                 log.log(Level.INFO, "PomModifier adding profile activation for localServer");
>                 profileId = "localServer";
>                 break;
> ```

This no longer makes sense as we do not have a local profile.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/93)*

**Comment by katheris** [comment]
Reviewed 1 of 82 files at r1.
Review status: 33 of 64 files reviewed at latest revision, 9 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/93)*

**Comment by katheris** [comment]
Reviewed 1 of 82 files at r1.
Review status: 34 of 64 files reviewed at latest revision, 9 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/93)*

**Comment by katheris** [comment]
Reviewed 1 of 82 files at r1.
Review status: 35 of 64 files reviewed at latest revision, 9 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/93)*

**Comment by katheris** [comment]
Reviewed 1 of 82 files at r1.
Review status: 36 of 64 files reviewed at latest revision, 9 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/93)*

**Comment by katheris** [comment]
Review status: 36 of 64 files reviewed at latest revision, 10 unresolved discussions.

---

*[liberty-starter-application/src/test/java/com/ibm/liberty/starter/it/api/v1/PayloadTest.java, line 61 at r1](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/93#-KWYGb99CZQOu_ZcpjFU:-KWYGb99CZQOu_ZcpjFV:bos2v5r) ([raw file](https://github.com/wasdev/tool.accelerate.core/blob/2a0da3596b4843b220d283734b61bb83a08d7d29/liberty-starter-application/src/test/java/com/ibm/liberty/starter/it/api/v1/PayloadTest.java#L61)):*
> ```Java
>         assertTrue("Expected compile-pom artifact. Found " + artifacts, artifacts.contains("compile-pom"));
>         assertEquals(6, dependencySize);
>     }
> ```

Consider checking that the other 3 dependencies are the ones we are expecting, not random ones that have been added.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/93)*

**Comment by katheris** [comment]
Reviewed 1 of 82 files at r1.
Review status: 37 of 64 files reviewed at latest revision, 10 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/93)*

**Comment by katheris** [comment]
Reviewed 1 of 82 files at r1.
Review status: 38 of 64 files reviewed at latest revision, 10 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/93)*

**Comment by katheris** [comment]
Reviewed 1 of 82 files at r1.
Review status: 39 of 64 files reviewed at latest revision, 10 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/93)*

**Comment by katheris** [comment]
Reviewed 1 of 82 files at r1.
Review status: 40 of 64 files reviewed at latest revision, 10 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/93)*

**Comment by katheris** [comment]
Reviewed 1 of 82 files at r1.
Review status: 41 of 64 files reviewed at latest revision, 10 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/93)*

**Comment by katheris** [comment]
Reviewed 1 of 82 files at r1.
Review status: 42 of 64 files reviewed at latest revision, 10 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/93)*

**Comment by katheris** [comment]
Reviewed 1 of 82 files at r1.
Review status: 43 of 64 files reviewed at latest revision, 10 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/93)*

**Comment by katheris** [comment]
Reviewed 1 of 82 files at r1.
Review status: 44 of 64 files reviewed at latest revision, 10 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/93)*

**Comment by katheris** [comment]
Reviewed 1 of 82 files at r1.
Review status: 45 of 64 files reviewed at latest revision, 10 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/93)*

**Comment by katheris** [comment]
Reviewed 1 of 82 files at r1.
Review status: 46 of 64 files reviewed at latest revision, 10 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/93)*

**Comment by katheris** [comment]
Reviewed 1 of 82 files at r1.
Review status: 47 of 64 files reviewed at latest revision, 11 unresolved discussions.

---

*[liberty-starter-application/src/test/java/com/ibm/liberty/starter/unit/LocalPomModifierTest.java, line 0 at r1](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/93#-KWYKVEtGD055kATltBy:-KWYKVEtGD055kATltBz:bvm4bpb) ([raw file](https://github.com/wasdev/tool.accelerate.core/blob/2a0da3596b4843b220d283734b61bb83a08d7d29/liberty-starter-application/src/test/java/com/ibm/liberty/starter/unit/LocalPomModifierTest.java#L0)):*
The local deploy option has not been removed from the UI so we should still have a test to verify that nothing breaks if you choose this option.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/93)*

**Comment by katheris** [comment]
Reviewed 1 of 82 files at r1.
Review status: 48 of 64 files reviewed at latest revision, 11 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/93)*

**Comment by katheris** [comment]
Reviewed 1 of 82 files at r1.
Review status: 49 of 64 files reviewed at latest revision, 11 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/93)*

**Comment by katheris** [comment]
Reviewed 11 of 82 files at r1.
Review status: 55 of 64 files reviewed at latest revision, 11 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/93)*

**Comment by katheris** [comment]
Reviewed 1 of 82 files at r1.
Review status: 56 of 64 files reviewed at latest revision, 11 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/93)*

**Comment by katheris** [comment]
Reviewed 12 of 82 files at r1.
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/93)*

**Comment by iainduncani** [comment]
*[liberty-starter-application/build.gradle, line 138 at r1](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/93#-KWY0DSBcpcuOqiR1_vi:-KWgD12L8yYTA_q30rq8:bfxdnem) ([raw file](https://github.com/wasdev/tool.accelerate.core/blob/2a0da3596b4843b220d283734b61bb83a08d7d29/liberty-starter-application/build.gradle#L138)):*
<details><summary><i>Previously, katheris (Katherine Stanley) wrote…</i></summary>
> I don't think using << is a good idea. I think this is no longer deemed best practice and I am struggling to find documentation to say exactly what using the symbols does. It makes it harder for other people to understand our builds.
</details>
I'm happy to change it if you think it will add clarity but I'm intrigued if it's now not considered best practice? It's still in the Gradle docs:

https://docs.gradle.org/current/userguide/tutorial_using_tasks.html

and I can't see anything to suggest it isn't best practice.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/93)*

**Comment by iainduncani** [comment]
Review status: 62 of 64 files reviewed at latest revision, 11 unresolved discussions.

---

*[README.md, line 68 at r1](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/93#-KWY0fbvrVIC-gDcozUT:-KWgO13xkWGWrGgY3Tb-:bke5swj) ([raw file](https://github.com/wasdev/tool.accelerate.core/blob/2a0da3596b4843b220d283734b61bb83a08d7d29/README.md#L68)):*
<details><summary><i>Previously, katheris (Katherine Stanley) wrote…</i></summary>
> This is a really long command, we should explain what this is doing or do something simpler.
</details>
Good suggestion, have updated to create a second task to create the server (localRun) so that we can separate out the test run with the local run.

---

*[liberty-starter-application/build.gradle, line 138 at r1](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/93#-KWY0DSBcpcuOqiR1_vi:-KWgHbzUcMUbHMNWl4Ny:b-hu5i7i) ([raw file](https://github.com/wasdev/tool.accelerate.core/blob/2a0da3596b4843b220d283734b61bb83a08d7d29/liberty-starter-application/build.gradle#L138)):*
<details><summary><i>Previously, iainduncani wrote…</i></summary>
> I'm happy to change it if you think it will add clarity but I'm intrigued if it's now not considered best practice? It's still in the Gradle docs:
> 
> https://docs.gradle.org/current/userguide/tutorial_using_tasks.html
> 
> and I can't see anything to suggest it isn't best practice.
</details>
This is now irrelevant as the forRunLibertyStart task does not exist anymore

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/93)*

**Comment by iainduncani** [comment]
*[README.md, line 27 at r1](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/93#-KWXz3Tv9jM9UiMe0W0W:-KWgOi-8iGotlR3wdgZ-:b-896fix) ([raw file](https://github.com/wasdev/tool.accelerate.core/blob/2a0da3596b4843b220d283734b61bb83a08d7d29/README.md#L27)):*
<details><summary><i>Previously, katheris (Katherine Stanley) wrote…</i></summary>
> Need to remove the word application here
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/93)*

**Comment by iainduncani** [comment]
*[liberty-starter-application/skeletons/base/src/main/liberty/config/server.xml, line 18 at r1](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/93#-KWY1QU59dRiFK59-maC:-KWgP2QKwUrBP4lH97Oa:btye3cb) ([raw file](https://github.com/wasdev/tool.accelerate.core/blob/2a0da3596b4843b220d283734b61bb83a08d7d29/liberty-starter-application/skeletons/base/src/main/liberty/config/server.xml#L18)):*
<details><summary><i>Previously, katheris (Katherine Stanley) wrote…</i></summary>
> Should this reference the target directory?
</details>
Possibly... I found this a weird comment, it is server two purposes. If you had just the server outside of an app accelerator environment (ie. you had used app accelerator to build a server package that was being passed around) then the comment would make no sense which is why I deleted the bit about the target, although as it still talks about building the application I should probably add it back in

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/93)*

**Comment by iainduncani** [comment]
Reviewed 2 of 82 files at r1.
Review status: 61 of 64 files reviewed at latest revision, 11 unresolved discussions.

---

*[liberty-starter-application/skeletons/specialFiles/pom.xml, line 113 at r1](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/93#-KWY4dnKWNuVsBUQIYMK:-KWgQF_nfJJPcw-FyjGo:b4pgfet) ([raw file](https://github.com/wasdev/tool.accelerate.core/blob/2a0da3596b4843b220d283734b61bb83a08d7d29/liberty-starter-application/skeletons/specialFiles/pom.xml#L113)):*
<details><summary><i>Previously, katheris (Katherine Stanley) wrote…</i></summary>
> Where is the version for this being declared?
</details>
Whoops, done now

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/93)*

**Comment by iainduncani** [comment]
*[liberty-starter-application/skeletons/specialFiles/pom.xml, line 307 at r1](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/93#-KWY6kprf-vTeJ7krttE:-KWgQfp4qihIV6aeQX7y:bqeh8q3) ([raw file](https://github.com/wasdev/tool.accelerate.core/blob/2a0da3596b4843b220d283734b61bb83a08d7d29/liberty-starter-application/skeletons/specialFiles/pom.xml#L307)):*
<details><summary><i>Previously, katheris (Katherine Stanley) wrote…</i></summary>
> We should consider putting this in a separate profile as if you run mvn install -DskipTests the tests will skip but the server will still start and stop.
</details>
Hasn't that always been the way? Although it is still a good suggestion, should we do it as a follow on piece do you think?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/93)*

**Comment by iainduncani** [comment]
Review status: 60 of 64 files reviewed at latest revision, 11 unresolved discussions.

---

*[liberty-starter-application/skeletons/specialFiles/pom.xml, line 307 at r1](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/93#-KWY6kprf-vTeJ7krttE:-KWgSyNk_BHt67NcDwuD:bygi2xm) ([raw file](https://github.com/wasdev/tool.accelerate.core/blob/2a0da3596b4843b220d283734b61bb83a08d7d29/liberty-starter-application/skeletons/specialFiles/pom.xml#L307)):*
<details><summary><i>Previously, iainduncani wrote…</i></summary>
> Hasn't that always been the way? Although it is still a good suggestion, should we do it as a follow on piece do you think?
</details>
Changed my mind, seemed small enough to just do here so now updated

---

*[liberty-starter-application/skeletons/specialFiles/pom.xml, line 349 at r1](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/93#-KWY7cz9PJU6GxX2GH4F:-KWgT8unGQP8A4kNhUxd:b-896fix) ([raw file](https://github.com/wasdev/tool.accelerate.core/blob/2a0da3596b4843b220d283734b61bb83a08d7d29/liberty-starter-application/skeletons/specialFiles/pom.xml#L349)):*
<details><summary><i>Previously, katheris (Katherine Stanley) wrote…</i></summary>
> We should change this to ${project.build.directory}/test-reports/it/failsafe-summary.xml to match the new package names.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/93)*

**Comment by iainduncani** [comment]
*[liberty-starter-application/skeletons/specialFiles/pom.xml, line 350 at r1](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/93#-KWY7ldR5KeP2Iibi1yA:-KWgTBPJ2_18A62fPGPe:b-896fix) ([raw file](https://github.com/wasdev/tool.accelerate.core/blob/2a0da3596b4843b220d283734b61bb83a08d7d29/liberty-starter-application/skeletons/specialFiles/pom.xml#L350)):*
<details><summary><i>Previously, katheris (Katherine Stanley) wrote…</i></summary>
> Same as above.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/93)*

**Comment by iainduncani** [comment]
*[liberty-starter-application/src/test/java/com/ibm/liberty/starter/unit/LocalPomModifierTest.java, line  at r1](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/93#-KWYKVEtGD055kATltBy:-KWgWaimUwYOGKTnRwdE:b-wwwbtl) ([raw file](https://github.com/wasdev/tool.accelerate.core/blob/2a0da3596b4843b220d283734b61bb83a08d7d29/liberty-starter-application/src/test/java/com/ibm/liberty/starter/unit/LocalPomModifierTest.java#L)):*
<details><summary><i>Previously, katheris (Katherine Stanley) wrote…</i></summary>
> The local deploy option has not been removed from the UI so we should still have a test to verify that nothing breaks if you choose this option.
</details>
All of these were moved to other unit tests and SetDefaultProfileCommand has a test for the local deploy type. RunLocalPayloadTest continues to do the local deploy option in the integration test.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/93)*

**Comment by iainduncani** [comment]
*[liberty-starter-application/src/main/java/com/ibm/liberty/starter/pom/SetDefaultProfileCommand.java, line 28 at r1](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/93#-KWYErw1SHFTmIBkpyrC:-KWg_2qeXJhONjRq6ZSx:b-896fix) ([raw file](https://github.com/wasdev/tool.accelerate.core/blob/2a0da3596b4843b220d283734b61bb83a08d7d29/liberty-starter-application/src/main/java/com/ibm/liberty/starter/pom/SetDefaultProfileCommand.java#L28)):*
<details><summary><i>Previously, katheris (Katherine Stanley) wrote…</i></summary>
> This no longer makes sense as we do not have a local profile.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/93)*

**Comment by katheris** [comment]
Reviewed 1 of 82 files at r1, 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/93)*

**Comment by iainduncani** [comment]
Review status: 63 of 64 files reviewed at latest revision, 1 unresolved discussion.

---

*[liberty-starter-application/src/test/java/com/ibm/liberty/starter/it/api/v1/PayloadTest.java, line 61 at r1](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/93#-KWYGb99CZQOu_ZcpjFU:-KWgt2mzxaSERetvo39D:b-896fix) ([raw file](https://github.com/wasdev/tool.accelerate.core/blob/2a0da3596b4843b220d283734b61bb83a08d7d29/liberty-starter-application/src/test/java/com/ibm/liberty/starter/it/api/v1/PayloadTest.java#L61)):*
<details><summary><i>Previously, katheris (Katherine Stanley) wrote…</i></summary>
> Consider checking that the other 3 dependencies are the ones we are expecting, not random ones that have been added.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/93)*

**Comment by katheris** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/wasdev/tool.accelerate.core/93)*

**Pull request merged**
